#!/usr/bin/env python
import os
import hashlib

cwd = os.getcwd()
print cwd
entries = os.listdir(cwd)

entry_list = []
for entry in entries:
    path = os.path.join(cwd, entry)
    print path
    digest = hashlib.sha224(entry_path).hexdigest()
    string = "%s %s" % (entry, digest)
    print string
    entry_list.append(string)


# import pdb; pdb.set_trace()



